dli_app/mod_reports/models.py
"""Models for the reports module

Author: Logan Gore
This file is responsible for defining models that belong in the reports module.
"""

import collections
import datetime
import glob
import os

import xlsxwriter

from dli_app import db

EXCEL_FILE_DIR = "excel-files"

report_fields = db.Table(
    'report_fields',
    db.Column('report_id', db.Integer, db.ForeignKey('report.id')),
    db.Column('field_id', db.Integer, db.ForeignKey('field.id')),
)


report_tags = db.Table(
    'report_tags',
    db.Column('report_id', db.Integer, db.ForeignKey('report.id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')),
)


chart_fields = db.Table(
    'chart_fields',
    db.Column('chart_id', db.Integer, db.ForeignKey('chart.id')),
    db.Column('field_id', db.Integer, db.ForeignKey('field.id')),
)


chart_tags = db.Table(
    'chart_tags',
    db.Column('chart_id', db.Integer, db.ForeignKey('chart.id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')),
)


def generate_date_list(start, end, step=None):
    """Generate a ds list along an interval"""
    if not step:
        step = 1
        if (end - start).days > 100:
            step = 7
        elif (end - start).days > 20:
            step = 3
    delta = datetime.timedelta(days=step)
    dates = []

    while start < end:
        dates.append(start)
        start += delta
    dates.append(end)
    return dates


def get_time_series_sequence(min_date):
    """Get the time series data that represents this chart in C3"""
    now = datetime.datetime.now()
    days = (now - min_date).days + 1
    ds_list = [min_date + datetime.timedelta(days=x) for x in range(0, days)]
    return sorted([x.strftime('%Y-%m-%d') for x in ds_list])


class Tag(db.Model):
    """Model for a Tag associated with a Report"""
    __tablename__ = "tag"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True, unique=True)

    def __init__(self, name):
        """Initialize a Tag model"""
        self.name = name

    def __repr__(self):
        """Return a descriptive representation of a Tag"""
        return '<Tag %r>' % self.name

    @classmethod
    def get_or_create(cls, name):
        """Either retrieve a tag or create it if it doesn't exist"""
        tag = Tag.query.filter_by(name=name).first()
        if tag is None:
            tag = Tag(name)
            db.session.add(tag)
            db.session.commit()
        return tag


class FieldType(db.Model):
    """Model for the type of a Field"""
    __tablename__ = "field_type"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32), index=True)

    def __init__(self, name):
        """Initialize a FieldType model"""
        self.name = name

    def __repr__(self):
        """Return a descriptive representation of a FieldType"""
        return '<Field Type %r>' % self.name

    def __eq__(self, other):
        """Determine if two FieldTypes are equal"""
        return other is not None and self.id == other.id


class FieldData(db.Model):
    """Model for the actual data stored in a Field"""
    __tablename__ = "field_data"
    id = db.Column(db.Integer, primary_key=True)
    ds = db.Column(db.String(16), index=True)
    field_id = db.Column(db.Integer, db.ForeignKey("field.id"))
    ivalue = db.Column(db.BigInteger)
    dvalue = db.Column(db.Float)
    svalue = db.Column(db.String(128))

    def __init__(self, ds, field, value):
        """Initialize a FieldData model"""
        FieldTypeConstants.reload()
        self.ds = ds
        self.field = field

        # Type checking should have already been done from the form
        if self.field.ftype == FieldTypeConstants.CURRENCY:
            parts = value.replace(',', '').replace('$', '').split('.')
            # Convert the value into cents to avoid any floating-point issues
            self.ivalue = int(parts[0]) * 100
            if len(parts) == 2:
                self.ivalue += int(parts[1])
        elif self.field.ftype == FieldTypeConstants.DOUBLE:
            self.dvalue = value
        elif self.field.ftype == FieldTypeConstants.INTEGER:
            self.ivalue = value
        elif self.field.ftype == FieldTypeConstants.STRING:
            self.svalue = value
        elif self.field.ftype == FieldTypeConstants.TIME:
            # Convert the value into seconds for convenience
            if ':' in value:
                parts = value.split(':')
            elif '.' in value:
                # Some people use '.' to denote minutes/seconds
                parts = value.split('.')
            else:
                # If no : or ., assume the value listed is seconds
                parts = ['0', value]

            # If the user listed something like ':00', make sure we can still parse
            parts = [x or '0' for x in parts]
            self.ivalue = int(parts[0]) * 60
            if len(parts) == 2:
                self.ivalue += int(parts[1])

    def __repr__(self):
        """Return a descriptive representation of a FieldData"""
        return '<FieldData of %r>' % self.field.name

    @property
    def value(self):
        """Property to easily retrieve the FieldData's value"""
        FieldTypeConstants.reload()
        ftype = self.field.ftype
        if ftype == FieldTypeConstants.CURRENCY:
            return float(self.ivalue) / 100
        elif ftype == FieldTypeConstants.DOUBLE:
            return self.dvalue
        elif ftype == FieldTypeConstants.INTEGER:
            return self.ivalue
        elif ftype == FieldTypeConstants.STRING:
            return self.svalue
        elif ftype == FieldTypeConstants.TIME:
            return self.ivalue
        else:
            raise NotImplementedError("ERROR: Type %s not supported!" % ftype)

    @property
    def pretty_value(self):
        """Property to easily retrieve a human-readable FieldData model"""
        FieldTypeConstants.reload()
        ftype = self.field.ftype
        if ftype == FieldTypeConstants.CURRENCY:
            dollars = self.ivalue / 100
            cents = self.ivalue % 100
            return "${dollars}.{cents:02d}".format(
                dollars=dollars,
                cents=cents,
            )
        elif ftype == FieldTypeConstants.DOUBLE:
            return self.dvalue
        elif ftype == FieldTypeConstants.INTEGER:
            return self.ivalue
        elif ftype == FieldTypeConstants.STRING:
            return self.svalue
        elif ftype == FieldTypeConstants.TIME:
            mins = self.ivalue / 60
            secs = self.ivalue % 60
            return "{mins}:{secs:02d}".format(
                mins=mins,
                secs=secs,
            )
        else:
            raise NotImplementedError("ERROR: Type %s not supported!" % ftype)


class Field(db.Model):
    """Model for a Field within a Report"""
    __tablename__ = "field"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32))
    ftype_id = db.Column(db.Integer, db.ForeignKey("field_type.id"))
    ftype = db.relationship(FieldType)
    department_id = db.Column(db.Integer, db.ForeignKey("department.id"))
    data_points = db.relationship(
        FieldData,
        backref='field',
        lazy='dynamic',
    )

    def __init__(self, name, ftype, department):
        """Initialize a Field model"""
        self.name = name
        self.ftype = ftype
        self.department = department

    def __repr__(self):
        """Return a descriptive representation of a Field"""
        return '<Field %r>' % self.name

    def get_data_for_date(self, ds, pretty=False):
        """Retrieve the FieldData instance for the given date stamp"""
        data_point = self.data_points.filter_by(ds=ds).first()
        if pretty:
            if data_point is not None:
                data_point = data_point.pretty_value
            else:
                data_point = ""
        return data_point

    @property
    def identifier(self):
        """Property to uniquely identify this Field"""
        return '{}: {}'.format(self.department.name, self.name)


class Report(db.Model):
    """Model for a DLI Report"""
    __tablename__ = "report"
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), index=True)
    name = db.Column(db.String(128))
    fields = db.relationship(
        Field,
        secondary=report_fields,
        backref='reports',
    )
    tags = db.relationship(
        Tag,
        secondary=report_tags,
        backref='reports',
    )

    def __init__(self, user, name, fields, tags):
        """Initialize a Report model"""
        self.user = user
        self.name = name
        self.fields = fields
        self.tags = tags

    def __repr__(self):
        """Return a descriptive representation of a Report"""
        return '<Report %r>' % self.name

    @property
    def tagnames(self):
        """Helper function to get the names of the Report's tags"""
        return [tag.name for tag in self.tags]

    def generate_filename(self, start_ds, end_ds):
        """Generate the filename for the Excel sheet for downloads"""
        return "{filename}-{start}-to-{end}.xlsx".format(
            filename=self.name,
            start=start_ds,
            end=end_ds,
        )

    def collect_dept_data_for_template(self, ds):
        """Collect all of the department data for this Report

        Collect department data for this Report on a given day in a format
        that is easy to template for render_template functions in Jinja2
        """

        dept_data = collections.defaultdict(list)
        for field in self.fields:
            dept_data[field.department.name].append(
                {
                    'name': field.name,
                    'value': field.get_data_for_date(ds, pretty=True),
                }
            )
        return dept_data

    def excel_filepath_for_ds(self, start_ds, end_ds):

dli_app/templates/reports/all.html
{% extends 'layout.html' %}
{% block body %}
  <div class="page-header">
    <h1>
      All Reports
      <small>
        <a href="{{ url_for('reports.my_reports') }}" class="btn btn-default">My Reports</a>
        <a href="{{ url_for('reports.create_report') }}" class="btn btn-primary"><span class="fa fa-plus"></span> New</a>

        <form method="POST" action="#" class="form-inline">
          {{ form.csrf_token }}
          <span class="input-group">
            <span class="input-group-btn">
              {{ form.filter_choices(class='form-control') }}
            </span>
            {{ form.search_text(class='form-control normal', placeholder='Search') }}
          </span>
          <span id="loading_spinner" class="fa fa-spinner fa-spin"></span>
        </form>
      </small>
    </h1>
  </div>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th></th>
        <th>Owner</th>
        <th>Tags</th>
      </tr>
    </thead>

    <tbody id="search_target">
      {% for report in reports.items %}
        <tr>
          <td>{{ report.id }}</td>
          <td>
            {% if report not in current_user.favorite_reports %}
              <a href="{{ url_for('reports.favorite_report', report_id=report.id) }}" data-method="post" class="btn btn-blank">
                <span class="fa fa-heart-o" aria-hidden="true"></span>
              </a>
            {% else %}
              <a href="{{ url_for('reports.unfavorite_report', report_id=report.id) }}" data-method="post" class="btn btn-blank">
                <span class="fa fa-heart" aria-hidden="true"></span>
              </a>
            {% endif %}
            <a href="{{ url_for('reports.view_report', report_id=report.id) }}">{{ report.name }}</a>
          </td>
          <td class="hover-options">
            <a href="{{ url_for('reports.submit_report_data', report_id=report.id) }}" class="btn btn-default btn-xs">Submit Data</a>

            {% if current_user.is_admin or report in current_user.reports %}
            <a href="{{ url_for('reports.edit_report', report_id=report.id) }}" class="btn btn-blank">
              <span class="fa fa-pencil" aria-hidden="true"></span>
            </a>

            <a href="{{ url_for('reports.delete_report', report_id=report.id) }}" data-method="post" data-confirm="Are you sure you want to delete this report?" class="btn btn-blank">
              <span class="fa fa-trash-o text-danger" aria-hidden="true"></span>
            </a>
            {% endif %}
          </td>
          <td>
            <a href="mailto:{{ report.user.email }}">{{ report.user.name }}</a>
          </td>
          <td>{{ ', '.join(report.tagnames) }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% if reports.has_prev %}
    <a class="btn btn-primary" href="{{ url_for('reports.my_reports') }}">First</a>
    <a class="btn btn-primary" href="{{ url_for('reports.my_reports', page_num=reports.prev_num) }}">&laquo; Prev</a>
  {% endif %}
  {% if reports.has_next %}
    <span class="pull-right">
      <a class="btn btn-primary" href="{{ url_for('reports.my_reports', page_num=reports.next_num) }}">Next &raquo;</a>
      <a class="btn btn-primary" href="{{ url_for('reports.my_reports', page_num=reports.pages) }}">Last</a>
    </span>
  {% endif %}
{% endblock %}

dli_app/templates/reports/all_charts.html
{% extends 'layout.html' %}
{% block body %}
  <div class="page-header">
    <h1>
      All Charts
      <small>
        <a href="{{ url_for('reports.my_charts') }}" class="btn btn-default">My Charts</a>
        <a href="{{ url_for('reports.create_chart') }}" class="btn btn-primary"><span class="fa fa-plus"></span> New</a>
      </small>
    </h1>
  </div>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th></th>
        <th>Owner</th>
        <th>Tags</th>
      </tr>
    </thead>

    <tbody>
      {% for chart in charts.items %}
        <tr>
          <td>{{ chart.id }}</td>
          <td>
            {% if chart not in current_user.favorite_charts %}
              <a href="{{ url_for('reports.favorite_chart', chart_id=chart.id) }}" data-method="post" class="btn btn-blank">
                <span class="fa fa-heart-o" aria-hidden="true"></span>
              </a>
            {% else %}
              <a href="{{ url_for('reports.unfavorite_chart', chart_id=chart.id) }}" data-method="post" class="btn btn-blank">
                <span class="fa fa-heart" aria-hidden="true"></span>
              </a>
            {% endif %}
            <a href="{{ url_for('reports.view_chart', chart_id=chart.id) }}">{{ chart.name }}</a>
          </td>
          <td class="hover-options">
          {% if current_user.is_admin or chart in current_user.charts %}
            <a href="{{ url_for('reports.edit_chart', chart_id=chart.id) }}" class="btn btn-blank">
              <span class="fa fa-pencil" aria-hidden="true"></span>
            </a>

            <a href="{{ url_for('reports.delete_chart', chart_id=chart.id) }}" data-method="post" data-confirm="Are you sure you want to delete this chart?" class="btn btn-blank">
              <span class="fa fa-trash-o text-danger" aria-hidden="true"></span>
            </a>
          {% endif %}
          </td>
          <td>
            <a href="mailto:{{ chart.user.email }}">{{ chart.user.name }}</a>
          </td>
          <td>{{ ', '.join(chart.tagnames) }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

dli_app/templates/reports/create.html
{% extends 'layout.html' %}
{% block body %}
  <div class="page-header">
    <h1>Create a Report</h1>
  </div>

  <div class="col-md-12">
    <form method="POST" action="{{ url_for('reports.create_report') }}" id="create_report_form">
      {{ form.csrf_token }}
      {{ form.user_id }}


      <div class="field-selector-header">
        <div class="row">
          <div class="col-md-4">
            <span class="input-group">
              <span class="input-group-addon">Name</span>
              {{ form.name(placeholder='My Report', class='form-control normal') }}
            </span>
          </div>

          <div class="col-md-4 col-md-offset-4">
            <div class="pull-right">
              <span class="input-group">
                <span class="input-group-addon">Tags</span>
                {{ form.tags(placeholder='tag1, tag2, etc.', class='form-control normal') }}
                <span class="input-group-btn">
                  <button type="submit" class="btn btn-primary">Create</button>
                </span>
              </span>
            </div>
          </div>
        </div>
      </div>

      <div class="field-selector field-selector-content" data-form-name="fields">
        <div class="selector-cell selector-cell-40">
          <div class="field-list">
            {% for department in form.departments %}
              <div class="department">
                <div class="department-name collapsed" data-toggle="collapse" data-target="#department_{{ department.id }}_fieldset">
                  {{ department.name }}
                </div>
                <div class="department-fieldset collapse" id="department_{{ department.id }}_fieldset">
                  {% if department.fields %}
                    {% for field in department.fields %}
                      <div class="department-field unadded" id="department-field-{{ field.id }}" data-department="{{ department.name }}" data-id="{{ field.id }}">
                        <a class="action add-field-btn"><span class="fa fa-plus"></span></a>
                        <a class="action remove-field-btn"><span class="fa fa-minus"></span></a>
                        {{ field.name }}
                      </div>
                    {% endfor %}
                  {% else %}
                    <span class="empty-fieldset">No fields for this department</span>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
          </div>
        </div>

        <div class="selector-cell selector-cell-60">
          <div class="selected-fields" id="selected_fields">
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

dli_app/templates/reports/create_chart.html
{% extends 'layout.html' %}
{% block body %}
  <div class="page-header">
    <h1>Create a Chart</h1>
  </div>

  <div class="col-md-12">
    <form method="POST" action="{{ url_for('reports.create_chart') }}" id="create_chart_form">
      {{ form.csrf_token }}
      {{ form.user_id }}


      <div class="field-selector-header">
        <div class="row">
          <div class="col-md-4">
            <span class="input-group">
              <span class="input-group-addon">Name</span>
              {{ form.name(placeholder='My Chart', class='form-control normal') }}
            </span>
          </div>

          <div class="col-md-2">
            <span class="input-group">
              <span class="input-group-addon">Type</span>
              {{ form.chart_type(class='form-control') }}
            </span>
          </div>

          <div class="col-md-2">
            {{ form.with_table }}
            <span class="control-label">
              Include Table?
            </span>
          </div>

          <div class="col-md-4">
            <div class="pull-right">
              <span class="input-group">
                <span class="input-group-addon">Tags</span>
                {{ form.tags(placeholder='tag1, tag2, etc.', class='form-control normal') }}
                <span class="input-group-btn">
                  <button type="submit" class="btn btn-primary">Create</button>
                </span>
              </span>
            </div>
          </div>
        </div>
      </div>


      <div class="field-selector field-selector-content" data-form-name="fields">
        <div class="selector-cell selector-cell-40">
          <div class="field-list">
            {% for department in form.departments %}
              <div class="department">
                <div class="department-name collapsed" data-toggle="collapse" data-target="#department_{{ department.id }}_fieldset">
                  {{ department.name }}
                </div>
                <div class="department-fieldset collapse" id="department_{{ department.id }}_fieldset">
                  {% if department.fields %}
                    {% for field in department.fields %}
                      <div class="department-field unadded" id="department-field-{{ field.id }}" data-department="{{ department.name }}" data-id="{{ field.id }}">
                        <a class="action add-field-btn"><span class="fa fa-plus"></span></a>
                        <a class="action remove-field-btn"><span class="fa fa-minus"></span></a>
                        {{ field.name }}
                      </div>
                    {% endfor %}
                  {% else %}
                    <span class="empty-fieldset">No fields for this department</span>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
          </div>
        </div>

        <div class="selector-cell selector-cell-60">
          <div class="selected-fields" id="selected_fields">
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

dli_app/templates/reports/download.html
{% extends 'layout.html' %}
{% block body %}
  <div class="page-header">
    <h1>Download Report: {{report.name }}</h1>
  </div>

  <div class="col-md-6">
    <form method="POST" action="{{ url_for('reports.download_report', report_id=report.id) }}" class="form-horizontal">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.start_date.label(class='control-label col-sm-2') }}
        <div class="col-sm-10">
          {{ form.start_date(class='form-control normal datepicker', type='text', placeholder='Click here to choose date') }}
        </div>
      </div>
      <div class="form-group">
        {{ form.end_date.label(class='control-label col-sm-2') }}
        <div class="col-sm-10">
          {{ form.end_date(class='form-control normal datepicker', type='text', placeholder='Click here to choose date') }}
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <a class="btn btn-danger" href="{{ url_for('reports.my_reports') }}">Back to Reports</a>
          <button onclick="javascript:displayWarningAndSubmit()" type="submit" class="btn btn-primary pull-right">Download Excel Data</button>
        </div>
      </div>
    </form>
    <div id="download_alert" class="alert alert-success fade in" style="display: none;">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <span class="glyphicon glyphicon-exclamation-sign"></span>
        Your Excel sheet is being prepared!<br>
        This may take a while, so sit tight and keep this page open!
    </div>
  </div>

  <script>
    function displayWarningAndSubmit() {
        $("#download_alert").fadeIn();
    }
  </script>

{% endblock %}

dli_app/templates/reports/edit.html
{% extends 'layout.html' %}
{% block body %}
  <div class="page-header">
    <h1>Edit "{{ report.name }}"</h1>
  </div>

  <div class="col-md-12">
    <form method="POST" action="{{ url_for('reports.edit_report', report_id=report.id) }}" id="edit_report_form">
      {{ form.csrf_token }}
      {{ form.user_id }}
      {{ form.report_id }}


      <div class="field-selector-header">
        <span class="lead">
          Report Name:
          {{ form.name(placeholder='My Report', class='normal') }}
        </span>
        <div class="pull-right">
          <span class="lead tag-list">
            Tags:
            {{ form.tags(class='normal', placeholder='tag1, tag2, etc.') }}
          </span>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      </div>

      <div class="field-selector field-selector-content" data-form-name="fields">
        <div class="selector-cell selector-cell-40">
          <div class="field-list">
            {% for department in form.departments %}
              <div class="department">
                <div class="department-name collapsed" data-toggle="collapse" data-target="#department_{{ department.id }}_fieldset">
                  {{ department.name }}
                </div>
                <div class="department-fieldset collapse" id="department_{{ department.id }}_fieldset">
                  {% if department.fields %}
                    {% for field in department.fields %}
                      {% if field in report.fields %}
                        <div class="department-field added" id="department-field-{{ field.id }}" data-department="{{ department.name }}" data-id="{{ field.id }}">
                          <a class="action add-field-btn"><span class="fa fa-plus"></span></a>
                          <a class="action remove-field-btn"><span class="fa fa-minus"></span></a>
                          {{ field.name }}
                        </div>
                      {% else %}
                        <div class="department-field unadded" id="department-field-{{ field.id }}" data-department="{{ department.name }}" data-id="{{ field.id }}">
                          <a class="action add-field-btn"><span class="fa fa-plus"></span></a>
                          <a class="action remove-field-btn"><span class="fa fa-minus"></span></a>
                          {{ field.name }}
                        </div>
                      {% endif %}
                    {% endfor %}
                  {% else %}
                    <span class="empty-fieldset">No fields for this department</span>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
          </div>
        </div>

        <div class="selector-cell selector-cell-60">
          <div class="selected-fields" id="selected_fields">
            {% for field in report.fields %}
              <div class="department-field" id="{{ field.id }}" data-id="{{ field.id }}">
                <div class="handle">
                  <span class="fa fa-th"></span>
                </div>
                <div class="content">
                  <span class="name">{{ field.name }}</span>
                  <span class="department">{{ field.department.name }}</span>
                </div>
                <div class="actions-cell">
                  <div class="actions">
                    <a class="btn btn-blank text-danger remove-field-btn"><span class="fa fa-remove"></span></a>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

dli_app/templates/reports/predict.html
{% extends 'layout.html' %}
{% block body %}
  <div class="page-header">
    <h1>Predictions based on the last {{ num_days }} days</h1>
  </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Field Name</th>
          <th>Prediction</th>
        </tr>
      </thead>

      <tbody>
          {% for field in predictions.keys() %}
          <tr>
            <td>{{ field.name }}</td>
            <td>{{ predictions[field] }}</td>
          </tr>
          {% endfor %}
      </tbody>
    </table>
{% endblock %}

dli_app/templates/reports/search.html
{% extends 'layout.html' %}
{% block body %}
  <div class="page-header">
    <h1>Search Reports</h1>
  </div>

  <div class="col-md-10">
    <form method="POST" action="{{ url_for('reports.search') }}" class="form-horizontal">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.filter_choices.label(class='control-label col-sm-2') }}
        <div class="col-sm-10">
          {{ form.filter_choices(class='form-control') }}
        </div>
      </div>
      <div class="form-group">
        {{ form.search_text.label(class='control-label col-sm-2') }}
        <div class="col-sm-10">
          {{ form.search_text(class='form-control') }}
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">Search</button>
        </div>
      </div>
    </form>
  </div>

{% endblock %}

dli_app/templates/reports/submit_data.html
{% extends 'layout.html' %}
{% block body %}
  <div class="page-header">
    <h1>
      Data Submission
      <small>{{ report.name }}</small>
      <br>
      <small>{{ department.name }} on {{ ds }}</small>
    </h1>
  </div>

  <p>
  Switch to data for <u><b><a href="{{ url_for('reports.submit_report_data', report_id=report.id, dept_id=department.id, ds='yesterday') }}">Yesterday</a></b></u> or <u><b><a href="{{ url_for('reports.submit_report_data', report_id=report.id, ds='today', dept_id=department.id) }}">Today</a></b></u>
  </p>

  <form id="form" method="POST" action="{{ url_for('reports.submit_report_data', report_id=report.id) }}" class="form-inline submit_data_change_form">
    {{ change_form.csrf_token }}
    <p class="">
      Switch to {{ change_form.department(class='form-control', onchange="this.form.submit()") }}
      on {{ change_form.date(class='form-control normal datepicker', type='text') }}
    </p>
  </form>


  <form method="POST" action="{{ url_for('reports.submit_report_data', report_id=report.id, ds=ds, dept_id=department.id) }}">
    {{ form.csrf_token }}
    {{ form.ds }}
    {% for field_set in chunked_fields %}
      <div class="col-sm-4 field-set">
        {% for field in field_set %}
          <div class="field">
            <span class="field-cell field-label">{{ form[field.name].label() }}</span>
            {% if field.ftype.name == "currency" %}
              <span class="field-cell field-input">{{ form[field.name](placeholder="000.00") }}</span>
            {% elif field.ftype.name == "integer" %}
              <span class="field-cell field-input">{{ form[field.name](placeholder="000", type="number") }}</span>
            {% elif field.ftype.name == "time" %}
              <span class="field-cell field-input">{{ form[field.name](placeholder="00:00") }}</span>
            {% elif field.ftype.name == "double" %}
              <span class="field-cell field-input">{{ form[field.name](placeholder="000.00", type="number", step="4") }}</span>
            {% elif field.ftype.name == "string" %}
              <span class="field-cell field-input">{{ form[field.name](placeholder="", type="text") }}</span>
            {% endif %}
          </div>
        {% endfor %}
      </div>

      {% if loop.index % 3 == 0 %}
        <div class="clearfix"></div>
      {% endif %}
    {% endfor %}

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Submit Data</button>
      </div>
    </div>
  </form>

  <script>
    $('#date').datepicker({
      format: "yyyy-mm-dd",
      maxDate: "+0d",
      endDate: "+0d"
    }).change(function(ev) {
      $('#form').submit();
    }).on('changeDate', function(ev) {
      $('#form').submit();
    });
  </script>
{% endblock %}